- hosts: localhost
  connection: local
  tasks:
    - name: Add required copr repositories
      become: yes
      command: dnf copr enable -y {{ item }}
      args:
        # Ansible dnf doesn't support copr
        # See https://github.com/ansible/ansible/issues/26673
        warn: no
      with_items:
        - thofmann/rofi
        - axeld/compton
        - riquito/polybar
        - nforro/i3-gaps
    - name: Install Packages
      become: yes
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - vim-enhanced
        - git
        - xclip
        - zsh
        # ansible needs this for dconf plugin
        - python2-psutil
        # Desktop environment
        - i3-gaps
        - compton
        - polybar
        - rofi
        - feh
        # To manage dotfiles
        - stow
        # Enpass dependencies
        - libXScrnSaver
        - lsof
        # Needed to enable chrome repo
        - fedora-workstation-repositories
    - name: Enable chrome repo
      become: yes
      command: dnf config-manager --set-enabled google-chrome
    - name: Install chrome
      become: yes
      package:
        name: google-chrome-stable
        state: latest
    - name: Get current user
      command: whoami
      register: current_user
    - name: Install oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
        update: no
    - name: Set zsh as the default shell
      become: yes
      user: name={{ current_user.stdout }} shell=/bin/zsh
    - name: Remove unused base packages
      become: yes
      package:
        name: "{{ item }}"
        state: absent
        autoremove: yes
      with_items:
        - libreoffice-calc
        - libreoffice-draw
        - libreoffice-impress
        - libreoffice-math
        - libreoffice-writer
        - libreoffice-core
        - libreofficekit
    - name: Find dotfiles
      register: files_matched
      find:
        paths: ./stowables
        file_type: directory
    - name: Lay down dotfiles
      command: stow {{ item | basename }} --target={{ ansible_env.HOME }}
      args:
        chdir: stowables
      with_items: "{{ files_matched | json_query('files[*].path') }}"
