- name: Add 1Password Key
  become: yes
  command:
    cmd: apt-key --keyring /usr/share/keyrings/1password.gpg adv --keyserver keyserver.ubuntu.com --recv-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
    creates: /usr/share/keyrings/1password.gpg
- name: Add 1Password Repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password.gpg] https://downloads.1password.com/linux/debian edge main
    state: present
- name: Install 1Password
  become: yes
  package:
    name: 1password
    update_cache: yes
    state: present
