---
- name: Install dependencies
  become: yes
  package:
    name: fedora-workstation-repositories
    state: latest
- name: Enable chrome repo
  become: yes
  command: dnf config-manager --set-enabled google-chrome
  args:
    # dnf ansible module doesn't permanently enable repos, I want it to do that
    warn: no
- name: Install chrome
  become: yes
  package:
    name: google-chrome-stable
    state: latest
