- name: Install stow
  become: yes
  package:
    name: stow
    state: latest
- name: Find dotfiles
  register: dotfiles
  find:
    paths: "{{ home_dir }}/.dotfiles/stowables"
    file_type: directory
- name: Lay down dotfiles
  command: stow {{ item | basename }} --target={{ home_dir }}
  args:
    chdir: "{{ home_dir }}/.dotfiles/stowables"
  with_items: "{{ dotfiles | json_query('files[*].path') }}"
