- name: Add Github CLI Apt Key
  become: yes
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    owner: root
    group: root
    mode: "0644"
- name: Add Github Repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
    state: present
- name: Install Github client
  become: yes
  package:
    name: gh
    update_cache: yes
    state: present
