- name: Enable autorandr repo
  become: yes
  command: dnf copr enable macieks/autorandr -y
  args:
    # Dnf module doesn't support copr
    warn: no
- name: Install packages needed for monitor control
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - autorandr
    - acpid
- name: Enable the autorandr service
  become: yes
  service:
    name: autorandr
    enabled: true
    state: started
- name: Enable the acpi service
  become: yes
  service:
    name: acpid
    enabled: true
    state: started
- name: Register laptop lid events
  become: yes
  copy:
    src: "{{ home_dir }}/.dotfiles/config_files/lidconf"
    dest: /etc/acpi/events/lidconf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
