- include: base-packages.yml
- include: peek.yml
- include: zsh.yml
- include: dotfiles.yml
- include: yarn.yml
- include: capslock-escape.yml
- include: file-watchers.yml
- include: pop-shell.yml
- include: 1password.yml
- include: gh.yml
