- include: chrome.yml
- include: zsh.yml
- include: dotfiles.yml
- include: enpass.yml
- name: Add required copr repositories
  become: yes
  command: dnf copr enable -y {{ item }}
  args:
    # Ansible dnf doesn't support copr
    # See https://github.com/ansible/ansible/issues/26673
    warn: no
  with_items:
    - thofmann/rofi
    - axeld/compton
    - dperson/neovim
- name: Install Packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - neovim
    - git
    - xclip
    - thefuck
    # Desktop environment
    - i3
    - i3lock
    - compton
    - rofi
    - feh
- name: Remove unused base packages
  become: yes
  package:
    name: "{{ item }}"
    state: absent
    autoremove: yes
  with_items:
    - libreoffice-calc
    - libreoffice-draw
    - libreoffice-impress
    - libreoffice-math
    - libreoffice-writer
    - libreoffice-core
    - libreofficekit
