- include: zsh.yml
- include: dotfiles.yml
- include: enpass.yml
- include: yarn.yml
- include: aws-cli.yml
- include: regolith.yml
- include: capslock-escape.yml
- name: Install Packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim
    - git
    - xclip
    - thefuck
    - scrot
    - htop
    - jq
    - direnv
    - net-tools
# Intellij and other file watching programs need to be able to watch a large number of files
- name: Increase inotify max watches
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    state: present
    value: 524288
- name: Remove unused base packages
  become: yes
  package:
    name: "{{ item }}"
    state: absent
    autoremove: yes
  with_items:
    - libreoffice-calc
    - libreoffice-draw
    - libreoffice-impress
    - libreoffice-math
    - libreoffice-writer
    - libreoffice-core
    - libreofficekit
