- name: Install Dependencies
  become: yes
  package:
    name: node-typescript
    state: present
- name: Download Pop Shell
  git:
    repo: https://github.com/pop-os/shell.git
    dest: "{{ home_dir }}/Development/popos-shell"
- name: Install Pop Shell
  command:
    chdir: ~/Development/popos-shell
    cmd: make local-install
    creates: "{{ home_dir }}/.local/share/gnome-shell/extensions/pop-shell@system76.com"

