- name: Add Yarn key
  become: yes
  apt_key:
    key: 72ECF46A56B4AD39C907BBB71646B01B86E50310
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
- name: Enable yarn repo
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
- name: Install Yarn
  become: yes
  package:
    name: yarn
    update_cache: yes
    state: present
