- name: Add Yarn key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
- name: Enable yarn repo
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
- name: Install Yarn
  become: yes
  package:
    name: yarn
    update_cache: yes
    state: latest
