- hosts: localhost
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
  connection: local
  roles:
    - desktop
    - ansible-jetbrains-toolbox
    - role: geerlingguy.docker
      become: yes
      docker_edition: 'ce'
      # Empty string means latest
      docker__compose_version: ""
      docker__users: ["{{ ansible_env.SUDO_USER }}"]
    - role: withmethod.google-chrome
      chrome_track: stable
      chrome_state: present
